import { day, week } from "./build";

export const W01 = week(
  1,
  "Survive the first week",
  "You can greet anyone, be polite, order something, and not panic when you don't understand.",
  [
    day(
      1,
      "Hello, please, thank you",
      "Walk into a shop, greet correctly, buy one thing, leave politely.",
      "boulangerie",
      [
        [
          "bonjour",
          "hello (all day until ~6pm)",
          "bon-ZHOOR",
          "Bonjour, un café s'il vous plaît.",
          "Hello, a coffee please.",
          {
            tip: "The 'on' is nasal — air through the nose, no N sound at the end.",
            note: "Not saying bonjour when you enter a shop reads as rude in France, so lead with it every time.",
            tags: ["greetings"],
          },
        ],
        [
          "bonsoir",
          "good evening (from ~6pm)",
          "bon-SWAHR",
          "Bonsoir, une table pour deux ?",
          "Good evening, a table for two?",
          { tags: ["greetings"] },
        ],
        [
          "s'il vous plaît",
          "please (polite / stranger)",
          "seel-voo-PLEH",
          "L'addition, s'il vous plaît.",
          "The bill, please.",
          {
            tip: "Runs together as three quick syllables — never say it slowly.",
            tags: ["politeness"],
          },
        ],
        [
          "merci",
          "thank you",
          "mair-SEE",
          "Merci, bonne journée !",
          "Thanks, have a good day!",
          { tags: ["politeness"] },
        ],
        [
          "merci beaucoup",
          "thank you very much",
          "mair-see bo-KOO",
          "Merci beaucoup, c'est très gentil.",
          "Thank you very much, that's very kind.",
          { tags: ["politeness"] },
        ],
        [
          "au revoir",
          "goodbye",
          "or-VWAHR",
          "Au revoir, merci !",
          "Goodbye, thanks!",
          { tip: "Swallow the first part: it sounds like 'or-vwar', not 'oh ruh voir'.", tags: ["greetings"] },
        ],
        [
          "excusez-moi",
          "excuse me (to get attention or squeeze past)",
          "ex-koo-zay-MWAH",
          "Excusez-moi, vous avez du pain ?",
          "Excuse me, do you have any bread?",
          { tags: ["politeness"] },
        ],
        [
          "pardon",
          "sorry (bumped into someone)",
          "par-DON",
          "Pardon, je ne vous avais pas vu.",
          "Sorry, I didn't see you.",
          { tags: ["politeness"] },
        ],
      ],
    ),

    day(
      2,
      "Yes, no, and rescuing yourself",
      "Say you don't understand and ask someone to slow down — without switching to English.",
      "greeting-neighbour",
      [
        ["oui", "yes", "WEE", "Oui, avec plaisir.", "Yes, with pleasure.", { tags: ["core"] }],
        ["non", "no", "NOH(n)", "Non, merci.", "No, thanks.", { tip: "Nasal again — no hard N.", tags: ["core"] }],
        [
          "je ne comprends pas",
          "I don't understand",
          "zhuh nuh kom-PRON pah",
          "Désolé, je ne comprends pas.",
          "Sorry, I don't understand.",
          {
            tip: "In speech most people drop the 'ne': 'zhuh kom-PRON pah'.",
            note: "French negation wraps the verb in ne ... pas, so the pas comes after the verb.",
            tags: ["survival"],
          },
        ],
        [
          "vous pouvez répéter ?",
          "can you say that again?",
          "voo poo-VAY ray-pay-TAY",
          "Pardon, vous pouvez répéter ?",
          "Sorry, can you say that again?",
          { tags: ["survival"] },
        ],
        [
          "plus lentement, s'il vous plaît",
          "more slowly, please",
          "ploo lont-MON seel-voo-PLEH",
          "Vous pouvez parler plus lentement, s'il vous plaît ?",
          "Can you speak more slowly, please?",
          { tip: "In 'plus lentement' the S is silent.", tags: ["survival"] },
        ],
        [
          "désolé",
          "sorry (apologising for yourself)",
          "day-zo-LAY",
          "Désolé, je suis en retard.",
          "Sorry, I'm late.",
          { note: "Add an extra -e if you're a woman: désolée — sounds identical.", tags: ["politeness"] },
        ],
        [
          "je parle un peu français",
          "I speak a little French",
          "zhuh parl uh(n) puh fron-SEH",
          "Je parle un peu français, mais pas très bien.",
          "I speak a little French, but not very well.",
          { tags: ["survival"] },
        ],
        [
          "comment on dit … en français ?",
          "how do you say … in French?",
          "ko-MON on dee … on fron-SEH",
          "Comment on dit 'receipt' en français ?",
          "How do you say 'receipt' in French?",
          { tags: ["survival"] },
        ],
      ],
    ),

    day(
      3,
      "Asking for what you want",
      "Order or request anything with one reliable pattern.",
      "cafe-order",
      [
        [
          "je voudrais",
          "I would like",
          "zhuh voo-DREH",
          "Je voudrais un croissant, s'il vous plaît.",
          "I'd like a croissant, please.",
          {
            note: "Use je voudrais rather than je veux ('I want') — je veux sounds blunt to a stranger.",
            tags: ["requests"],
          },
        ],
        [
          "un / une",
          "a (masculine / feminine)",
          "UH(n) / OON",
          "Un café et une eau, s'il vous plaît.",
          "A coffee and a water, please.",
          {
            note: "Every French noun is masculine or feminine, so learn each new noun with its un or une attached.",
            tags: ["core"],
          },
        ],
        [
          "je prends",
          "I'll have / I'll take (ordering)",
          "zhuh PRON",
          "Je prends le menu du jour.",
          "I'll have the set menu.",
          { tags: ["requests", "food"] },
        ],
        [
          "vous avez … ?",
          "do you have …?",
          "voo-za-VAY",
          "Vous avez du pain complet ?",
          "Do you have wholemeal bread?",
          { tip: "Link the S: 'voo-ZA-vay'. French glues words together.", tags: ["requests"] },
        ],
        [
          "c'est combien ?",
          "how much is it?",
          "say kom-BYEH(n)",
          "C'est combien, la tarte ?",
          "How much is the tart?",
          { tags: ["money"] },
        ],
        [
          "et avec ça ?",
          "anything else? (what they'll ask you)",
          "ay a-vek SAH",
          "— Et avec ça ? — C'est tout, merci.",
          "— Anything else? — That's all, thanks.",
          { tags: ["shopping", "listening"] },
        ],
        [
          "c'est tout",
          "that's all",
          "say TOO",
          "Non, c'est tout, merci.",
          "No, that's all, thanks.",
          { tags: ["shopping"] },
        ],
        [
          "voilà",
          "here you go / there it is",
          "vwah-LAH",
          "Voilà, bonne journée !",
          "Here you go, have a good day!",
          { tip: "Used constantly — handing something over, finishing a thought, agreeing.", tags: ["core"] },
        ],
      ],
    ),

    day(
      4,
      "Numbers 1–20 and paying",
      "Understand a price said out loud and pay without guessing.",
      "supermarket",
      [
        [
          "un, deux, trois",
          "1, 2, 3",
          "UH(n), DUH, TRWAH",
          "Trois croissants, s'il vous plaît.",
          "Three croissants, please.",
          { tags: ["numbers"] },
        ],
        [
          "quatre, cinq, six",
          "4, 5, 6",
          "KATR, SANK, SEESS",
          "Cinq euros, s'il vous plaît.",
          "Five euros, please.",
          { tip: "Six alone is 'seess', but before a noun it's 'see': six pommes = 'see pom'.", tags: ["numbers"] },
        ],
        [
          "sept, huit, neuf, dix",
          "7, 8, 9, 10",
          "SET, WEET, NUHF, DEESS",
          "Dix euros cinquante.",
          "Ten euros fifty.",
          { tags: ["numbers"] },
        ],
        [
          "onze, douze, treize",
          "11, 12, 13",
          "ONZ, DOOZ, TREZ",
          "Il est onze heures.",
          "It's eleven o'clock.",
          { tags: ["numbers"] },
        ],
        [
          "quatorze, quinze, seize",
          "14, 15, 16",
          "ka-TORZ, KANZ, SEZ",
          "Quinze euros, ça va ?",
          "Fifteen euros, is that OK?",
          { tags: ["numbers"] },
        ],
        [
          "dix-sept, dix-huit, dix-neuf, vingt",
          "17, 18, 19, 20",
          "dee-SET, dee-ZWEET, deez-NUHF, VAN",
          "Vingt euros, s'il vous plaît.",
          "Twenty euros, please.",
          { tip: "The T in vingt is silent.", tags: ["numbers"] },
        ],
        [
          "par carte",
          "by card",
          "par KART",
          "Je paie par carte.",
          "I'll pay by card.",
          { tags: ["money"] },
        ],
        [
          "en espèces",
          "in cash",
          "on ess-PESS",
          "Je peux payer en espèces ?",
          "Can I pay in cash?",
          { tags: ["money"] },
        ],
      ],
    ),

    day(
      5,
      "The magic connectors",
      "Glue words that make broken French sound like real French.",
      "boulangerie",
      [
        [
          "et",
          "and",
          "AY",
          "Un café et un croissant.",
          "A coffee and a croissant.",
          { tags: ["connectors"] },
        ],
        [
          "mais",
          "but",
          "MEH",
          "J'aime bien, mais c'est trop cher.",
          "I like it, but it's too expensive.",
          { tags: ["connectors"] },
        ],
        [
          "aussi",
          "also / too",
          "o-SEE",
          "Moi aussi, je voudrais un thé.",
          "Me too, I'd like a tea.",
          { tags: ["connectors"] },
        ],
        [
          "un peu",
          "a little",
          "uh(n) PUH",
          "Juste un peu, merci.",
          "Just a little, thanks.",
          { tags: ["quantity"] },
        ],
        [
          "beaucoup",
          "a lot",
          "bo-KOO",
          "Il y a beaucoup de monde aujourd'hui.",
          "There are a lot of people today.",
          { tags: ["quantity"] },
        ],
        [
          "très",
          "very",
          "TREH",
          "C'est très bon !",
          "It's very good!",
          { tags: ["core"] },
        ],
        [
          "trop",
          "too / too much",
          "TRO",
          "C'est trop cher pour moi.",
          "It's too expensive for me.",
          { tags: ["core"] },
        ],
        [
          "alors",
          "so / well then",
          "a-LOR",
          "Alors, je prends celui-là.",
          "Right then, I'll take that one.",
          { tip: "Great stalling word while your brain catches up.", tags: ["connectors", "fillers"] },
        ],
      ],
    ),

    day(
      6,
      "How are you, and answering it",
      "Handle the exchange that starts every single conversation.",
      "greeting-neighbour",
      [
        [
          "ça va ?",
          "how's it going? / you OK?",
          "sa VAH",
          "Salut, ça va ?",
          "Hi, how's it going?",
          {
            tip: "Same two words answer it too: 'Ça va.' Tone does the work.",
            tags: ["small talk"],
          },
        ],
        [
          "comment allez-vous ?",
          "how are you? (polite)",
          "ko-mon-ta-lay-VOO",
          "Bonjour madame, comment allez-vous ?",
          "Hello madam, how are you?",
          { tags: ["small talk", "politeness"] },
        ],
        [
          "ça va bien, merci",
          "I'm well, thanks",
          "sa va BYEH(n) mair-SEE",
          "Ça va bien, merci, et vous ?",
          "I'm well thanks, and you?",
          { tags: ["small talk"] },
        ],
        [
          "et vous ?",
          "and you? (polite)",
          "ay VOO",
          "Très bien, et vous ?",
          "Very well, and you?",
          {
            note: "Use vous with strangers and anyone older or senior; tu only once they use it with you.",
            tags: ["small talk"],
          },
        ],
        [
          "pas mal",
            "not bad",
          "pah MAL",
          "Pas mal, et toi ?",
          "Not bad, and you?",
          { tags: ["small talk"] },
        ],
        [
          "ça peut aller",
          "getting by / so-so",
          "sa puh-ta-LAY",
          "Bof, ça peut aller.",
          "Meh, getting by.",
          { tags: ["small talk"] },
        ],
        [
          "salut",
          "hi / bye (friends only)",
          "sa-LOO",
          "Salut, à demain !",
          "Bye, see you tomorrow!",
          { note: "Never open with salut to a shopkeeper or someone older — use bonjour.", tags: ["greetings"] },
        ],
        [
          "bonne journée",
          "have a good day",
          "bon zhoor-NAY",
          "Merci, bonne journée !",
          "Thanks, have a good day!",
          { tags: ["greetings"] },
        ],
      ],
    ),

    day(
      7,
      "Week 1 test",
      "Prove you can run a whole shop or café exchange unaided.",
      "cafe-order",
      [
        [
          "je vais prendre",
          "I'm going to have",
          "zhuh vay PRONDR",
          "Je vais prendre un café, s'il vous plaît.",
          "I'm going to have a coffee, please.",
          { tags: ["requests", "food"] },
        ],
        [
          "sur place ou à emporter ?",
          "eat in or take away? (what they'll ask)",
          "soor PLASS oo a om-por-TAY",
          "— Sur place ou à emporter ? — À emporter, merci.",
          "— Eat in or take away? — Take away, thanks.",
          { tags: ["food", "listening"] },
        ],
        [
          "ça fait combien ?",
          "how much does that come to?",
          "sa fay kom-BYEH(n)",
          "Ça fait combien en tout ?",
          "How much is that all together?",
          { tags: ["money"] },
        ],
        [
          "je peux avoir … ?",
          "can I have …?",
          "zhuh puh a-VWAR",
          "Je peux avoir un verre d'eau ?",
          "Can I have a glass of water?",
          { tags: ["requests"] },
        ],
        [
          "d'accord",
          "OK / agreed",
          "da-KOR",
          "D'accord, très bien.",
          "OK, great.",
          { tags: ["core"] },
        ],
        [
          "avec plaisir",
          "with pleasure / gladly",
          "a-vek play-ZEER",
          "— Merci ! — Avec plaisir.",
          "— Thanks! — My pleasure.",
          { tags: ["politeness"] },
        ],
        [
          "je ne sais pas",
          "I don't know",
          "zhuh nuh say PAH",
          "Je ne sais pas, désolé.",
          "I don't know, sorry.",
          { tip: "Spoken fast it becomes 'shay pah'.", tags: ["survival"] },
        ],
        [
          "bonne soirée",
          "have a good evening",
          "bon swah-RAY",
          "Au revoir, bonne soirée !",
          "Goodbye, have a good evening!",
          { tags: ["greetings"] },
        ],
      ],
    ),
  ],
);
